[build]
  publish = "public"   # keep your small index.html; fine for API-only

[functions]
  node_bundler = "esbuild"
  included_files = ["src/uploads/**"]   # optional: ships committed assets (read-only)

# Send /api/... to the function and preserve the rest of the path
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
